name: CI

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  msi-deploy:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'
          cache: gradle
      - name: Build msi-file and upload build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: packageMsi
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.FIREBASE_AUTH }}'
      - id: 'upload-file'
        name: Upload msi file to Storage
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './build/compose/binaries/main/msi'
          destination: '${{ secrets.STORAGE_BUCKET }}'
          glob: 'announcer-*.msi'
