name: CI

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-build:
    permissions:
      contents: read
      packages: write
    runs-on: windows-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
          cache: gradle
      - name: Extract credentials file to resources
        run: echo ${{ secrets.FIREBASE_AUTH_BASE64 }} > ./src/main/resources/${{ secrets.AUTH_FILE_NAME }}
      - name: Build msi distributable
        uses: gradle/gradle-build-action@v2
        env:
          FIREBASE_AUTH_BASE64: '${{ secrets.AUTH_FILE_NAME }}'
          STORAGE_BUCKET: '${{ secrets.STORAGE_BUCKET }}'
        with:
          arguments: packageMsi
      - uses: actions/upload-artifact@v3
        name: Upload distibutable to Github Packages
        with:
          path: './build/compose/binaries/main/msi/announcer-*.msi'
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.FIREBASE_AUTH }}'
      - id: 'upload-file'
        name: Upload distibutable file to Google Storage
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: './build/compose/binaries/main/msi'
          destination: '${{ secrets.STORAGE_BUCKET }}'
          parent: false
          glob: 'announcer-*.msi'
