name: CI

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  msi-deploy:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Build msi-file and upload build
        run: ./gradlew uploadPackageToFirebase
